### ISSUE TITLE
Model.aux unaccessible 

### ISSUE THREAD

**Issue by Jkings300** [do-mpc/do-mpc#264]
I create a Model('continuous') instance and populate it with several variables, rhs equations and (crucially for this issue) expressions (using the .set_expression() method).

I try to access the aux variables like I would access states (model.x --> model.aux). I picked this up in my own code, but the example in the model.aux API reference gives the same issue. here is the example code.
```
import do_mpc
model = do_mpc.model.Model('continuous')
model.set_variable('_x','temperature', 4) # 4 states
dt = model.x['temperature',0]- model.x['temperature', 1]
model.set_expression('dtemp', dt)
# Query:
model.aux['dtemp', 0] # 0th element of variable
model.aux['dtemp']    # all elements of variable
```

This raises the following stacktrace:
Traceback (most recent call last):
  File "<ipython-input-9-f5a5b072e442>", line 6, in <module>
    model.aux['dtemp', 0] # 0th element of variable
  File "\do_mpc\model.py", line 642, in aux
    return self._getvar('_aux_expression')
  File "\do_mpc\model.py", line 375, in _getvar
    sym_struct = self._convert2struct(sym_dict)
  File "\do_mpc\model.py", line 1032, in _convert2struct
    entry(name, shape = var.shape) for var, name in zip(var_dict['var'], var_dict['name'])
TypeError: list indices must be integers or slices, not str

I'm running do_mpc 4.3.3 on Windows 10, which I pip installed.

I think the issue is in the property getter for aux in do_mpc\model.py: l.610-642. Specifically in the `return` statement:
642  `return self._getvar('_aux_expression')`

I suspect it should actually read:
642  `return self._getvar('_aux')`
as with all the other getters.

The _aux property is a dict with the required fields, whereas the _aux_expression property is a list of CasadiStructEntry.

This will be my first issue raised on git and I aim to create a pull request with the fix. I apologise if I've missed something. I am not entirely sure what all the correct steps are for contributing

**Comment by Jkings300** [comment]
Tested v4.3.5 after PR #265. Works like a charm.
