### ISSUE TITLE
erro when set up simulator from model

### ISSUE THREAD

**Issue by TiaHao** [do-mpc/do-mpc#390]
Hi,

Thanks for the useful tool. I am trying to simply set up the model and simulator with this:
model_type = 'discrete' # either 'discrete' or 'continuous'
model = do_mpc.model.Model(model_type)
simulator = do_mpc.simulator.Simulator(model)

but I get this error: 
Traceback (most recent call last):
  File "/Users/wenjinhao/opt/anaconda3/envs/kwr_env/lib/python3.11/site-packages/IPython/core/interactiveshell.py", line 3505, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-4-415a60e411ae>", line 1, in <module>
    simulator = do_mpc.simulator.Simulator(model)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/wenjinhao/opt/anaconda3/envs/kwr_env/lib/python3.11/site-packages/do_mpc/simulator.py", line 133, in __init__
    do_mpc.model.IteratedVariables.__init__(self)
  File "/Users/wenjinhao/opt/anaconda3/envs/kwr_env/lib/python3.11/site-packages/do_mpc/model/_iteratedvariables.py", line 40, in __init__
    self._x0 = self.model._x(0.0)

is this something systematic or I made some mistake? thanks for help in advance!

**Comment by TiaHao** [comment]
solved
